ALTER TABLE "character_documents" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "character_voices" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "characters" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "costs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "document_chunks" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "environments" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "project_audio_assets" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scene_templates" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "scripts" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "source_items" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "universe_projects" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE "universes" ENABLE ROW LEVEL SECURITY;--> statement-breakpoint
CREATE POLICY "character_documents_select" ON "character_documents" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "character_documents_insert" ON "character_documents" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "character_documents_delete" ON "character_documents" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "voices_select" ON "character_voices" AS PERMISSIVE FOR SELECT TO "authenticated" USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "voices_insert" ON "character_voices" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "voices_update" ON "character_voices" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "voices_delete" ON "character_voices" AS PERMISSIVE FOR DELETE TO "authenticated" USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "characters_select" ON "characters" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "characters_insert" ON "characters" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "characters_update" ON "characters" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "characters_delete" ON "characters" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "costs_select" ON "costs" AS PERMISSIVE FOR SELECT TO "authenticated" USING (video_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "chunks_select" ON "document_chunks" AS PERMISSIVE FOR SELECT TO "authenticated" USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "chunks_insert" ON "document_chunks" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "chunks_delete" ON "document_chunks" AS PERMISSIVE FOR DELETE TO "authenticated" USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "environments_select" ON "environments" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "environments_insert" ON "environments" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "environments_update" ON "environments" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "environments_delete" ON "environments" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "jobs_select" ON "jobs" AS PERMISSIVE FOR SELECT TO "authenticated" USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "jobs_insert" ON "jobs" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "audio_assets_select" ON "project_audio_assets" AS PERMISSIVE FOR SELECT TO "authenticated" USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "audio_assets_insert" ON "project_audio_assets" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "audio_assets_delete" ON "project_audio_assets" AS PERMISSIVE FOR DELETE TO "authenticated" USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))))));--> statement-breakpoint
CREATE POLICY "scene_templates_select" ON "scene_templates" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scene_templates_insert" ON "scene_templates" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scene_templates_update" ON "scene_templates" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scene_templates_delete" ON "scene_templates" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scripts_select" ON "scripts" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scripts_insert" ON "scripts" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scripts_update" ON "scripts" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "scripts_delete" ON "scripts" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "source_items_select" ON "source_items" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "source_items_insert" ON "source_items" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "source_items_update" ON "source_items" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "source_items_delete" ON "source_items" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "projects_select" ON "universe_projects" AS PERMISSIVE FOR SELECT TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "projects_insert" ON "universe_projects" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "projects_update" ON "universe_projects" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "projects_delete" ON "universe_projects" AS PERMISSIVE FOR DELETE TO "authenticated" USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid())))));--> statement-breakpoint
CREATE POLICY "universes_select" ON "universes" AS PERMISSIVE FOR SELECT TO "authenticated" USING (organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))));--> statement-breakpoint
CREATE POLICY "universes_insert" ON "universes" AS PERMISSIVE FOR INSERT TO "authenticated" WITH CHECK (organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))));--> statement-breakpoint
CREATE POLICY "universes_update" ON "universes" AS PERMISSIVE FOR UPDATE TO "authenticated" USING (organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))));--> statement-breakpoint
CREATE POLICY "universes_delete" ON "universes" AS PERMISSIVE FOR DELETE TO "authenticated" USING (organization_id = ANY((SELECT ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()))) AND EXISTS (SELECT 1 FROM organization_members WHERE organization_id = universes.organization_id AND user_id = auth.uid() AND role IN ('owner', 'admin')));