ALTER POLICY "billing_events_select" ON "billing_events" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "billing_events_insert" ON "billing_events" TO authenticated WITH CHECK (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "character_documents_select" ON "character_documents" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "character_documents_insert" ON "character_documents" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "character_documents_update" ON "character_documents" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "character_documents_delete" ON "character_documents" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "voices_select" ON "character_voices" TO authenticated USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "voices_insert" ON "character_voices" TO authenticated WITH CHECK (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "voices_update" ON "character_voices" TO authenticated USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "voices_delete" ON "character_voices" TO authenticated USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "characters_select" ON "characters" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "characters_insert" ON "characters" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "characters_update" ON "characters" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "characters_delete" ON "characters" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "costs_select" ON "costs" TO authenticated USING (video_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "costs_insert" ON "costs" TO authenticated WITH CHECK (video_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "credit_balances_select" ON "credit_balances" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "credit_balances_update" ON "credit_balances" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "credit_ledger_select" ON "credit_ledger" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "credit_ledger_insert" ON "credit_ledger" TO authenticated WITH CHECK (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "chunks_select" ON "document_chunks" TO authenticated USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "chunks_insert" ON "document_chunks" TO authenticated WITH CHECK (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "chunks_update" ON "document_chunks" TO authenticated USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "chunks_delete" ON "document_chunks" TO authenticated USING (character_id IN (SELECT id FROM characters WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "environments_select" ON "environments" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "environments_insert" ON "environments" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "environments_update" ON "environments" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "environments_delete" ON "environments" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "jobs_select" ON "jobs" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "jobs_insert" ON "jobs" TO authenticated WITH CHECK (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "jobs_update" ON "jobs" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "jobs_delete" ON "jobs" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "audio_assets_select" ON "project_audio_assets" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "audio_assets_insert" ON "project_audio_assets" TO authenticated WITH CHECK (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "audio_assets_update" ON "project_audio_assets" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "audio_assets_delete" ON "project_audio_assets" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "project_effects_select" ON "project_effects" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "project_effects_insert" ON "project_effects" TO authenticated WITH CHECK (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "project_effects_update" ON "project_effects" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "project_effects_delete" ON "project_effects" TO authenticated USING (project_id IN (SELECT id FROM universe_projects WHERE universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)))));--> statement-breakpoint
ALTER POLICY "referrals_select" ON "referrals" TO authenticated USING (referrer_org_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)) OR referee_org_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "referrals_insert" ON "referrals" TO authenticated WITH CHECK (referrer_org_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "scene_templates_select" ON "scene_templates" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scene_templates_insert" ON "scene_templates" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scene_templates_update" ON "scene_templates" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scene_templates_delete" ON "scene_templates" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scripts_select" ON "scripts" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scripts_insert" ON "scripts" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scripts_update" ON "scripts" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "scripts_delete" ON "scripts" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "source_items_select" ON "source_items" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "source_items_insert" ON "source_items" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "source_items_update" ON "source_items" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "source_items_delete" ON "source_items" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "subscription_extras_select" ON "subscription_extras" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "subscription_extras_insert" ON "subscription_extras" TO authenticated WITH CHECK (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "subscription_extras_update" ON "subscription_extras" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "projects_select" ON "universe_projects" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "projects_insert" ON "universe_projects" TO authenticated WITH CHECK (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "projects_update" ON "universe_projects" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "projects_delete" ON "universe_projects" TO authenticated USING (universe_id IN (SELECT id FROM universes WHERE organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text))));--> statement-breakpoint
ALTER POLICY "universes_select" ON "universes" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "universes_insert" ON "universes" TO authenticated WITH CHECK (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "universes_update" ON "universes" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "universes_delete" ON "universes" TO authenticated USING (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)) AND EXISTS (SELECT 1 FROM organization_members WHERE organization_id = universes.organization_id AND user_id = auth.uid()::text AND role IN ('owner', 'admin')));--> statement-breakpoint
ALTER POLICY "video_styles_select" ON "video_styles" TO authenticated USING (is_builtin = 1 OR organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "video_styles_insert" ON "video_styles" TO authenticated WITH CHECK (organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "video_styles_update" ON "video_styles" TO authenticated USING (is_builtin = 0 AND organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));--> statement-breakpoint
ALTER POLICY "video_styles_delete" ON "video_styles" TO authenticated USING (is_builtin = 0 AND organization_id = ANY(ARRAY(SELECT organization_id FROM organization_members WHERE user_id = auth.uid()::text)));