"""Final H.264 export optimized for YouTube Shorts."""

from __future__ import annotations

import asyncio
import logging
import shlex
from pathlib import Path

logger = logging.getLogger(__name__)


async def export_final(
    video_with_text_path: str,
    output_path: str,
    aspect_ratio: str = "9:16",
) -> str:
    """Final encode optimized for YouTube/social export.

    Specs:
    - Resolution: 1080x1920 (9:16) or 1920x1080 (16:9)
    - Codec: H.264 (libx264)
    - Profile: high
    - Preset: slow (quality over speed)
    - CRF: 18 (high quality)
    - FPS: 30
    - Audio: AAC 192kbps
    - Pixel format: yuv420p
    - Faststart: yes (moov atom at start for streaming)

    Returns path to final .mp4
    """
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        "ffmpeg", "-y",
        "-i", video_with_text_path,
        "-vf", f"scale={'1920:1080' if aspect_ratio == '16:9' else '1080:1920'}:force_original_aspect_ratio=decrease,"
               f"pad={'1920:1080' if aspect_ratio == '16:9' else '1080:1920'}:(ow-iw)/2:(oh-ih)/2",
        "-c:v", "libx264",
        "-profile:v", "high",
        "-preset", "slow",
        "-crf", "18",
        "-r", "30",
        "-c:a", "aac",
        "-b:a", "192k",
        "-ar", "44100",
        "-pix_fmt", "yuv420p",
        "-movflags", "+faststart",
        "-metadata", "comment=Generated by LoreKit",
        output_path,
    ]

    logger.info("Exporting final video: %s", output_path)
    await _run_ffmpeg(cmd)

    file_size = Path(output_path).stat().st_size
    logger.info(
        "Export complete: %s (%.1f MB)",
        output_path,
        file_size / (1024 * 1024),
    )
    return output_path


async def _run_ffmpeg(cmd: list[str]) -> None:
    """Run an ffmpeg command via subprocess."""
    logger.debug("Running: %s", " ".join(shlex.quote(c) for c in cmd))

    proc = await asyncio.create_subprocess_exec(
        *cmd,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    stdout, stderr = await proc.communicate()

    if proc.returncode != 0:
        raise RuntimeError(
            f"ffmpeg failed (exit {proc.returncode}): {stderr.decode(errors='replace')}"
        )
